# Generated by Django 4.0.3 on 2022-05-09 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
        ('user', '0003_like_like_unique_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_like', to='audio.track', unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
