# Generated by Django 4.0.3 on 2022-05-09 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
        ('user', '0004_alter_like_track_id_alter_like_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_like', to='audio.track'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('type', models.TextField()),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_notification', to='audio.track')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_notification', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
