# Generated by Django 4.0.3 on 2022-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_like_track_id_alter_like_user_id_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.TextField(),
        ),
    ]
