# Generated by Django 4.0.3 on 2022-05-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_bio_alter_profile_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.JSONField(blank=True),
        ),
    ]
